from tokenize import TokenError

from selenium import webdriver
import time
driver=webdriver.Chrome(executable_path=r'C:\Users\Ashutosh Charchi\PycharmProjects\Python\chromedriver.exe')
driver.get("https://mail.rediff.com/cgi-bin/login.cgi")
email=driver.find_element_by_xpath('//*[@id="login1"]')
email.send_keys("alumni.space")
passtext=open("password.text",'r')
password=driver.find_element_by_xpath('//*[@id="password"]')
password.send_keys(passtext.read())
keep_me_signIn_bt=driver.find_element_by_xpath('//*[@id="remember"]')
keep_me_signIn_bt.click()
login_bt=driver.find_element_by_xpath('/html/body/div[1]/div[1]/div[2]/div[2]/div[1]/div/form/div[2]/div[6]/div[1]/input')
login_bt.click()
writeMail_box=driver.find_element_by_xpath('//*[@id="boxscroll"]/li[1]/a')
writeMail_box.click()
time.sleep(15)
To_send_email=driver.find_element_by_xpath('//*[@id="TO_IDcmp2"]')
To_send_email.send_keys("devraj.prida.22@gmail.com")
subject_box=driver.find_element_by_xpath('//*[@id="rd_compose_cmp2"]/ul/li[4]/input')
subject_box.send_keys("Hi Devraj this is Autogenrated mail for testing purpose .. ")
#time.sleep(1)
#print("check 0")
#past_bt=driver.find_element_by_css_selector(".cke_button__paste_icon")
#past_bt.click()
#print("check 1")
#Main_email_context=driver.find_element_by_class_name('.cke_editable')
#print("check 2 ")
#Main_email_context.clear()
#print("check 3")
#Main_email_context.send_keys("Dear Piyush it's test it ")
time.sleep(1)
send_mail_bt=driver.find_element_by_xpath('//*[@id="rd_compose_cmp2"]/div[1]/a[1]')
 send_mail_bt.click()
time.sleep(5)
logout_bt=driver.find_element_by_xpath('/html/body/div[4]/div[1]/div/div[2]/a[2]')
login_bt.click()
time.sleep(5)
driver.close()
